public class ST_Constants {

    public static final String ERROR_UNSUPPORTED_BROWSER = 'Sorry, Internet Explorer 8 is not supported by this app. Please use another browser.';
    public static final String ERROR_NON_ACCENTURE_EMAIL = 'Please specify an accenture email address';
    public static final String ERROR_INVALID_TOKEN_CODE = 'Invalid token code.';
    public static final Integer TOKEN_CODE_LENGTH = 32;
    public static final String REFRESH_TOKEN_QUERY = 'Select Id, TokenCode__c FROM Transcript__c';
    public static final String LOGIN_INSTRUCTION = 'Please enter your Accenture Email then click Send Token. Your code will be sent to your email shortly after.';
    
    public static final String TARGET_OBJECT_ID = '003L000000QRX8p';//'003e0000006tdbT';
    
    }